name: calipy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pyyaml
  - construct=2.9
  - pyqtgraph
  - pip
  - pip:
        - scipy
        - imageio[pyav]
        - bbo-svidreader
        - opencv-contrib-python-headless==4.10.0.84
        - pyqt
        - bbo-ccvtools
        - bbo-calibcamlib
        - bbo-calibcam
